name: Build Windows

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compiler
        run: cargo build --release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: branchgen-windows
          path: target/release/branchgen.exe
